name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Limpia la caché de npm para evitar conflictos
      - run: npm cache clean --force

      # Instala dependencias con --legacy-peer-deps para evitar errores de ERESOLVE
      - run: npm ci --legacy-peer-deps && npm run build

      # Asegura que Firebase CLI esté instalado antes del despliegue
      - run: npm install -g firebase-tools

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DOTA2LIGA_CA479 }}
          channelId: live
          projectId: dota2liga-ca479
